language: c

dist: trusty
sudo: false

matrix:
  include:
      # g++ 6 on Linux with C++11
    - env: COMPILER=g++-6 STANDARD=11
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
     # g++ 8 on Linux with C++11
    - env: COMPILER=g++-8 STANDARD=11
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

      # Apple clang on OS X with C++11
    - env: BUILD=Debug STANDARD=11
      compiler: clang
      os: osx
      # clang 6.0 on Linux with C++11 
    - env: COMPILER=clang++-6.0 STANDARD=11
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-6.0
      # clang 4.0 on Linux with C++11
    - env: COMPILER=clang++-4.0 STANDARD=11
      compiler: clang
      addons:
        apt:
          update: true
          packages:
            - clang-4.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-4.0
      # g++ 4.8 on Linux with C++11
    - env: COMPILER=g++-4.8 STANDARD=11
      compiler: gcc

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; export CC=${COMPILER}; ${CXX} --version; fi

script: make